<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>CloudCheck</AssemblyName>
    <RootNamespace>CloudLinkGuard</RootNamespace>
    <ApplicationIcon>Assets\CloudLinkGuard.ico</ApplicationIcon>
    <Version>1.4.4</Version>
    <AssemblyVersion>1.4.4.0</AssemblyVersion>
    <FileVersion>1.4.4.0</FileVersion>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="Assets\CloudLinkGuard.ico" />
    <EmbeddedResource Include="..\Rules\CloudLinkGuard-Merge.yaml"
                      Link="Rules\CloudLinkGuard-Merge.yaml"
                      LogicalName="CloudLinkGuard.Rules.CloudLinkGuard-Merge.yaml" />
  </ItemGroup>
</Project>
