<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>PuffRoute</AssemblyName>
    <RootNamespace>PuffRoute</RootNamespace>
    <ApplicationIcon>Assets\PuffRoute.ico</ApplicationIcon>
    <Version>1.2.7</Version>
    <AssemblyVersion>1.2.7.0</AssemblyVersion>
    <FileVersion>1.2.7.0</FileVersion>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="Assets\PuffRoute.ico" />
    <EmbeddedResource Include="..\Rules\PuffRoute-Merge.yaml"
                      Link="Rules\PuffRoute-Merge.yaml"
                      LogicalName="PuffRoute.Rules.PuffRoute-Merge.yaml" />
  </ItemGroup>
</Project>
